- name: "ensure apache2 is installed"
  apt:
    pkg: apache2

- name: copy template index 
  template: 
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644
  notify: restart apache2
